### ISSUE TITLE
not loss.py or evaluator.py 

### ISSUE THREAD

**Issue by hhsm** [h4nwei/STI-VQA#1]
main.py

```
from loss import Loss 
# from train_single_stage import Trainer
from train_new import Trainer
from evaluator import Evaluator
```

there are not loss.py or evaluator.py in this repo

**Comment by h4nwei** [comment]
Hi @hhsm, thanks for the kind reminder. I will update the code repository after the holiday. Stay tuned.

**Comment by zhaoyimeng123** [comment]
main.py

from evaluator import Evaluator
from network.vsfa_new import VSFA_new

there are not evaluator.py or network.vsfa_new in this repo
