### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by zhaoyimeng123** [h4nwei/STI-VQA#2]
main.py

from evaluator import Evaluator
from network.vsfa_new import VSFA_new

there are not evaluator.py or network.vsfa_new in this repo

**Comment by zhaoyimeng123** [comment]
from evaluator import Evaluator
here are not evaluator.py in this repo

**Comment by h4nwei** [comment]
Hi @zhaoyimeng123 ,

Thanks for pointing it out. I have updated the codes. Please let me know if there are any other issues.

Best,
Hanwei

**Comment by zhaoyimeng123** [comment]
Thank you for your help and timely response.

Best regards

**Comment by zhaoyimeng123** [comment]
Thank you for your help and timely response.

Best regards
